apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapi-docker-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-webapi-docker-k8s
  template:
    metadata:
      labels:
        app: dotnet-webapi-docker-k8s
    spec:
      containers:
        - name: dotnet-webapi-docker-k8s
          image: kiransarode/dotnet_webapi_docker_k8s_image:3
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 250Mi