apiVersion: v1
kind: Service
metadata:
  name: dotnet-webapi-docker-k8s-service
spec:
  selector:
    app: dotnet-webapi-docker-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer